### ISSUE TITLE
[FY] Not working for Windows platform

### ISSUE THREAD

**Issue by ZhiweiDuan** [zxdawn/weather_data#1]
On the Windows platform, running download_fy.sh with Git bash, the following problems occur:
./download_fy.sh: line 11: lftp: command not found
how to solve this problem

**Comment by zxdawn** [comment]
You need to install lftp first.

If you're using Anaconda, you can install it easily:
```
conda install -c conda-forge lftp
```

Otherwise, you may have to add `lftp` to the PATH.

**Comment by ZhiweiDuan** [comment]
I am on the Windows planeform， but the&nbsp;conda-forge lftp is for the linux.
Would I have to change the platform?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zxdawn/weather_data"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 晚上8:16
收件人:&nbsp;"zxdawn/weather_data"<weather_data@noreply.github.com&gt;;
抄送:&nbsp;"duanzhiwei"<1830794421@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zxdawn/weather_data] problem with the running of the bash script (#1)





 
You need to install lftp first.
 
If you're using Anaconda, you can install it easily:
 conda install -c conda-forge lftp  
Otherwise, you may have to add lftp to the PATH.

**Comment by zxdawn** [comment]
You can try Windows subsystem for Linux or look for another Windows terminal tool of downloading ftp files.

**Comment by ZhiweiDuan** [comment]
Thanks for your help, I have installed it on the linux system, and successfully download the data.


Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zxdawn/weather_data"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 晚上11:31
收件人:&nbsp;"zxdawn/weather_data"<weather_data@noreply.github.com&gt;;
抄送:&nbsp;"duanzhiwei"<1830794421@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zxdawn/weather_data] problem with the running of the bash script (#1)





 
You can try Windows subsystem for Linux or look for another Windows terminal tool of downloading ftp files.
