### ISSUE TITLE
[FY] Unable to locate element

### ISSUE THREAD

**Issue by ZhiweiDuan** [zxdawn/weather_data#2]
When I use the modified code to download Fengyun satellite data in batches, sometimes it succeeds, and sometimes I encounter the following problems:

NoSuchElementException: no such element: Unable to locate element: {"method":"link text","selector":"My Orders"}
  (Session info: chrome=86.0.4240.75)

How to solve this problem？

**Comment by zxdawn** [comment]
@ZhiweiDuan Could you check whether the page is loaded successfully? Maybe, your browser needs more time to load the page.
You can increase the sleeping time in the [function of login](https://github.com/zxdawn/weather_data/blob/98ef2cb5dead2113d14045977651b1fc3d0fad54/FY/fy.py#L43).

**Comment by ZhiweiDuan** [comment]
thank you very much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zxdawn/weather_data"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月18日(星期天) 晚上6:18
收件人:&nbsp;"zxdawn/weather_data"<weather_data@noreply.github.com&gt;;
抄送:&nbsp;"duanzhiwei"<1830794421@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [zxdawn/weather_data] running problem (#2)





 
@ZhiweiDuan Could you check whether the page is loaded successfully? Maybe, your browser needs more time to load the page.
 You can increase the sleeping time in the function of login.
